import React, { useEffect } from 'react';
import { toast } from 'sonner';
import { ReportMetadata } from '@/hooks/useReportActions';
import './print.css';

// Import all report pages
import ResearchReportPage from '@/pages/projects/reports/ResearchReportPage';
import CompetitorReportPage from '@/pages/projects/reports/CompetitorReportPage';
import BusinessPlanReportPage from '@/pages/projects/reports/BusinessPlanReportPage';
import FinancialReportPage from '@/pages/projects/reports/FinancialReportPage';
import MarketingReportPage from '@/pages/projects/reports/MarketingReportPage';

interface PrintableReportProps {
  reportType: string;
  reportData: any;
  projectData: any;
  reportMetadata: any;
  filename: string;
  meta: ReportMetadata;
  onComplete: () => void;
}

export default function PrintableReport({
  reportType,
  reportData,
  projectData,
  reportMetadata,
  filename,
  meta,
  onComplete
}: PrintableReportProps) {

  useEffect(() => {
    // 1. Prepare for printing by setting the document title (used as default filename in "Save as PDF")
    const originalTitle = document.title;
    const cleanName = filename.replace('.pdf', '');
    document.title = cleanName;

    const toastId = toast.loading('Preparing high-quality document...');

    // 2. Wait for charts to animate and images to load
    const timer = setTimeout(() => {
      toast.loading('Opening print dialog — choose "Save as PDF"', { id: toastId, duration: 8000 });
      
      // 3. Trigger browser native print
      window.print();

      // 4. Cleanup after print dialog is closed
      document.title = originalTitle;
      toast.success('Document ready. Select "Save as PDF" to download.', { id: toastId, duration: 4000 });
      
      // Remove from portal
      onComplete();
    }, 1500);

    return () => {
      clearTimeout(timer);
      document.title = originalTitle;
      toast.dismiss(toastId);
    };
  }, [filename, onComplete]);

  const renderContent = () => {
    const props = {
      hideNavigation: true,
      overrideData: reportData,
      overrideProject: projectData,
      overrideReportMetadata: reportMetadata,
      printMode: true // This completely strips the interactive ReportShell!
    };

    switch (reportType) {
      case 'research': return <ResearchReportPage {...props} />;
      case 'competitor': return <CompetitorReportPage {...props} />;
      case 'business-plan': return <BusinessPlanReportPage {...props} />;
      case 'finance': return <FinancialReportPage {...props} />;
      case 'marketing': return <MarketingReportPage {...props} />;
      default: return <div>Unknown Report Type: {reportType}</div>;
    }
  };

  const generatedTimestamp = new Date().toLocaleString();

  return (
    <div id="print-root">
      
      {/* ──────────────────────────────────────────────────────────────────
          PRINT-ONLY HEADER 
          ────────────────────────────────────────────────────────────────── */}
      <div className="print-report-header mb-8 pb-4 border-b-2 border-indigo-600">
        <span className="block text-xs font-semibold text-indigo-600 uppercase tracking-widest mb-2">
          StartupPilot AI — Confidential Report
        </span>
        <h1 className="text-3xl font-bold text-slate-900 mb-1 leading-tight">
          {meta.reportTypeStr || 'Report'}
        </h1>
        <div className="text-sm text-slate-500 mt-2 flex flex-wrap gap-4">
          {meta.projectName && <span>Project: <strong>{meta.projectName}</strong></span>}
          {meta.industry && <span>Industry: {meta.industry}</span>}
          {meta.country && <span>Country: {meta.country}</span>}
          {meta.dateStr && <span>Generated: {meta.dateStr}</span>}
          {meta.provider && <span className="capitalize">Provider: {meta.provider.replace('_', ' ')}</span>}
        </div>
      </div>

      {/* ──────────────────────────────────────────────────────────────────
          PURE REPORT CONTENT (No scrollbars, no h-screen, no wrappers)
          ────────────────────────────────────────────────────────────────── */}
      <div className="print-report-content w-full">
        {renderContent()}
      </div>

      {/* ──────────────────────────────────────────────────────────────────
          PRINT-ONLY FOOTER
          ────────────────────────────────────────────────────────────────── */}
      <div className="print-report-footer mt-12 pt-4 border-t border-slate-200 text-center text-xs text-slate-400">
        Generated by StartupPilot AI &nbsp;·&nbsp; {generatedTimestamp} &nbsp;·&nbsp; {meta.reportTypeStr} &nbsp;·&nbsp; {meta.projectName}
      </div>

    </div>
  );
}
