import { useState } from 'react'
import { Link } from 'react-router-dom'
import { motion } from 'framer-motion'
import {
  ArrowLeft, Download, Printer, Copy, Check, RefreshCw, Loader,
  FileText, AlertCircle
} from 'lucide-react'
import { Button } from '@/components/ui/button'
import { cn } from '@/lib/utils'
import api from '@/lib/api'
import { Breadcrumb } from '@/components/navigation/Breadcrumb'
import { useExportPDF } from '@/hooks/useExportPDF'

interface ReportShellProps {
  projectId: string
  reportType: string   // e.g. 'research', 'competitor', 'business-plan', 'finance', 'marketing'
  title: string
  subtitle?: string
  accentColor?: string
  children: React.ReactNode
  rawData?: any        // used for markdown export
  loading?: boolean
  error?: string | null
  onReload?: () => void
  hideNavigation?: boolean
  projectData?: any
  reportMetadata?: any
}

function buildMarkdown(title: string, data: any): string {
  const lines: string[] = [`# ${title}`, '', `*Generated by StartupPilot AI*`, '']
  const walk = (obj: any, depth = 0): void => {
    if (Array.isArray(obj)) {
      obj.forEach((item, i) => {
        if (typeof item === 'object') { lines.push(''); walk(item, depth + 1) }
        else lines.push(`${'  '.repeat(depth)}- ${item}`)
      })
    } else if (obj && typeof obj === 'object') {
      Object.entries(obj).forEach(([key, val]) => {
        const label = key.replace(/_/g, ' ').replace(/\b\w/g, c => c.toUpperCase())
        if (typeof val === 'object') {
          lines.push(`${'#'.repeat(Math.min(depth + 2, 6))} ${label}`)
          walk(val, depth + 1)
        } else {
          lines.push(`**${label}:** ${val}`)
        }
      })
    } else if (obj != null) {
      lines.push(String(obj))
    }
  }
  if (data) walk(data)
  return lines.join('\n')
}

function SkeletonCard({ h = 40 }: { h?: number }) {
  return <div className={`w-full animate-pulse rounded-xl bg-muted`} style={{ height: `${h * 4}px` }} />
}

export function ReportSkeleton() {
  return (
    <div className="space-y-6 max-w-5xl">
      <SkeletonCard h={12} />
      <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
        {[...Array(4)].map((_, i) => <SkeletonCard key={i} h={24} />)}
      </div>
      <SkeletonCard h={48} />
      <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
        {[...Array(2)].map((_, i) => <SkeletonCard key={i} h={40} />)}
      </div>
      <SkeletonCard h={32} />
    </div>
  )
}

export default function ReportShell({
  projectId,
  reportType,
  title,
  subtitle,
  accentColor = 'from-violet-600 to-indigo-600',
  children,
  rawData,
  loading = false,
  error = null,
  onReload,
  hideNavigation = false,
  projectData,
  reportMetadata,
}: ReportShellProps) {
  const [copied, setCopied] = useState(false)
  const [regenerating, setRegenerating] = useState(false)
  const [regenError, setRegenError] = useState<string | null>(null)
  const [regenProgress, setRegenProgress] = useState<{ step: string; percent: number } | null>(null)
  const [regenSuccess, setRegenSuccess] = useState(false)
  const { exportToPDF, isExporting } = useExportPDF()

  const handleCopy = async () => {
    try {
      setCopied(true)
      const res = await api.get(`/projects/${projectId}/reports/${reportType}/markdown`)
      await navigator.clipboard.writeText(res.data)
      setTimeout(() => setCopied(false), 2000)
    } catch (err) {
      console.error('Failed to copy markdown', err)
      setCopied(false)
    }
  }

  const handlePrint = () => window.print()

  const handleRegenerate = async () => {
    setRegenerating(true)
    setRegenError(null)
    setRegenProgress(null)
    setRegenSuccess(false)
    try {
      await api.post(`/projects/${projectId}/reports/${reportType}/regenerate`)
      
      let attempts = 0
      const maxAttempts = 60 // 120 seconds max
      const poll = setInterval(async () => {
        attempts++
        try {
          const res = await api.get(`/projects/${projectId}/reports/${reportType}`)
          
          if (res.status === 202) {
            const detail = res.data?.detail
            if (detail && typeof detail === 'object') {
              setRegenProgress({
                step: detail.progress_step || 'Regenerating...',
                percent: detail.progress_percent || 0
              })
            }
            return
          }
          
          // Success — report is completed
          clearInterval(poll)
          setRegenerating(false)
          setRegenProgress(null)
          setRegenSuccess(true)
          
          setTimeout(() => {
            setRegenSuccess(false)
            onReload?.()
          }, 1500)
        } catch (pollErr: any) {
          if (pollErr?.response?.status === 202) {
            const detail = pollErr.response.data?.detail
            if (detail && typeof detail === 'object') {
              setRegenProgress({
                step: detail.progress_step || 'Regenerating...',
                percent: detail.progress_percent || 0
              })
            }
            return
          }
          // Any other error (404 = failed, 500 = error) — stop polling
          clearInterval(poll)
          setRegenerating(false)
          setRegenProgress(null)
          setRegenError(pollErr?.response?.data?.detail || 'Regeneration failed')
        }
        
        if (attempts >= maxAttempts) {
          clearInterval(poll)
          setRegenerating(false)
          setRegenError('Timeout waiting for regeneration')
        }
      }, 2000)
    } catch (err: any) {
      setRegenError(err?.response?.data?.detail || 'Failed to start regeneration')
      setRegenerating(false)
    }
  }

  if (loading) return <ReportSkeleton />

  if (error) {
    return (
      <div className="max-w-5xl space-y-4">
        {!hideNavigation && <Breadcrumb projectId={projectId} projectName={subtitle?.split(' · ')[0] || 'Project'} reportType={reportType} />}
        {!hideNavigation && (
          <Link to={`/projects/${projectId}`}>
            <button className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
              <ArrowLeft className="w-4 h-4" /> Back to Project
            </button>
          </Link>
        )}
        <div className="rounded-xl border border-destructive/30 bg-destructive/5 p-8 text-center space-y-4">
          <AlertCircle className="w-10 h-10 text-destructive mx-auto" />
          <p className="font-semibold text-foreground text-lg">{title} — Not Generated Yet</p>
          <p className="text-muted-foreground text-sm max-w-md mx-auto">{error}</p>
          {onReload && (
            <Button onClick={onReload} variant="outline" size="sm">
              Try Again
            </Button>
          )}
        </div>
      </div>
    )
  }

  return (
    <div id="report-pdf-content" className="space-y-6 max-w-5xl print:max-w-full">
      {!hideNavigation && <Breadcrumb projectId={projectId} projectName={subtitle?.split(' · ')[0] || 'Project'} reportType={reportType} />}
      
      {/* Back navigation + export toolbar */}
      <motion.div initial={{ opacity: 0, y: -8 }} animate={{ opacity: 1, y: 0 }} className="space-y-4">
        <div className="flex items-center justify-between flex-wrap gap-3 print:hidden">
          {!hideNavigation && (
            <Link to={`/projects/${projectId}`}>
              <button className="flex items-center gap-1.5 text-sm text-muted-foreground hover:text-foreground transition-colors">
                <ArrowLeft className="w-4 h-4" /> Back to Project
              </button>
            </Link>
          )}
          <div className="flex items-center gap-2 ml-auto">
            {regenError && (
              <span className="text-xs text-destructive">{regenError}</span>
            )}
            <Button
              variant={regenSuccess ? "default" : "outline"}
              size="sm"
              onClick={handleRegenerate}
              disabled={regenerating || regenSuccess}
              className={cn("gap-1.5 h-8 text-xs transition-colors", regenSuccess && "bg-green-600 hover:bg-green-700 text-white")}
            >
              {regenSuccess ? (
                <><Check className="w-3 h-3" /> Report Updated</>
              ) : regenerating ? (
                <><Loader className="w-3 h-3 animate-spin" /> {regenProgress ? `${regenProgress.percent}%` : 'Regenerating…'}</>
              ) : (
                <><RefreshCw className="w-3 h-3" /> Regenerate</>
              )}
            </Button>
            <Button variant="outline" size="sm" onClick={handleCopy} className="gap-1.5 h-8 text-xs">
              {copied ? <><Check className="w-3 h-3 text-green-500" /> Copied</> : <><Copy className="w-3 h-3" /> Copy MD</>}
            </Button>
            <Button 
              variant="outline" 
              size="sm" 
              disabled={isExporting}
              className="gap-1.5 h-8 text-xs"
              onClick={async () => {
                const projName = projectData?.business_name?.replace(/\s+/g, '') || 'Project'
                const dateStr = new Date().toISOString().split('T')[0]
                const fileName = `${projName}_${title.replace(/\s+/g, '')}_${dateStr}.pdf`
                const success = await exportToPDF('report-pdf-content', fileName)
                if (success) {
                  alert('PDF downloaded successfully.')
                }
              }}
            >
              {isExporting ? <Loader className="w-3 h-3 animate-spin" /> : <Download className="w-3 h-3" />}
              {isExporting ? 'Generating PDF...' : 'Download PDF'}
            </Button>
            <Button variant="outline" size="sm" onClick={handlePrint} className="gap-1.5 h-8 text-xs">
              <Printer className="w-3 h-3" /> Print
            </Button>
          </div>
        </div>

        {/* Report header with gradient accent */}
        <div className="relative overflow-hidden rounded-2xl border border-border bg-card shadow-sm">
          <div className={cn('absolute inset-x-0 top-0 h-1 bg-gradient-to-r', accentColor)} />
          <div className="px-7 py-6">
            <div className="flex items-start gap-4">
              <div className={cn('w-12 h-12 rounded-xl bg-gradient-to-br flex items-center justify-center shrink-0', accentColor)}>
                <FileText className="w-6 h-6 text-white" />
              </div>
              <div>
                <h1 className="text-2xl font-bold text-foreground tracking-tight">{title}</h1>
                
                <div className="flex flex-wrap items-center gap-x-4 gap-y-1 mt-2 text-sm text-muted-foreground">
                  {projectData && (
                    <>
                      <span className="font-medium text-foreground">Project: {projectData.business_name || 'Unknown'}</span>
                      {projectData.industry && <span>Industry: {projectData.industry}</span>}
                      {projectData.country && <span>Country: {projectData.country}</span>}
                    </>
                  )}
                  {reportMetadata && (
                    <>
                      {reportMetadata.version && <span>Version: {reportMetadata.version}</span>}
                      {reportMetadata.updated_at && (
                        <span>Generated: {new Date(reportMetadata.updated_at).toLocaleDateString('en-US', { month: 'long', day: 'numeric', year: 'numeric' })}</span>
                      )}
                      {reportMetadata.provider_used && <span className="capitalize">Provider: {reportMetadata.provider_used.replace('_', ' ')}</span>}
                    </>
                  )}
                </div>
                
                {regenerating && (
                  <div className="mt-3">
                    <p className="text-xs text-primary flex items-center gap-1.5 font-medium">
                      <Loader className="w-3 h-3 animate-spin" />
                      {regenProgress ? `${regenProgress.step} (${regenProgress.percent}%)` : 'Regenerating this report...'}
                    </p>
                    <div className="h-1.5 w-64 bg-primary/10 rounded-full mt-2 overflow-hidden">
                      <motion.div 
                        className="h-full bg-primary" 
                        initial={{ width: 0 }} 
                        animate={{ width: `${regenProgress?.percent || 0}%` }} 
                        transition={{ duration: 0.5 }}
                      />
                    </div>
                  </div>
                )}
              </div>
            </div>
          </div>
        </div>
      </motion.div>

      {/* Page content */}
      <div className="space-y-6 print:space-y-4">
        {children}
      </div>
    </div>
  )
}
